// This file is automatically generated. Do not modify.
// TODO: Replace the object below with the one from your Firebase project settings.
export const firebaseConfig = {
  "projectId": "studio-949642570-67b0d",
  "appId": "1:1008781888305:web:14d90c4c96a5ae99df7e10",
  "apiKey": "AIzaSyBW4uCk-7OMXBYDeRPKmM69GQ2ndxF-7Vs",
  "authDomain": "studio-949642570-67b0d.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "1008781888305"
};
